import type { Metadata } from "next";
import { LocalizedTitle } from "@/components/localized-title";

export const metadata: Metadata = { title: "Syarat & Ketentuan" };

const sections = [
  ["1. Tentang Layanan", "DowaLabs adalah layanan digital berbasis membership yang menyediakan akses ke AI Product Studio, AI Canvas, penghapus latar belakang, color grading, portrait style, pustaka prompt, template, tutorial, dan fitur lain yang tersedia di dashboard. Fitur, kuota, tampilan, dan integrasi pihak ketiga dapat diperbarui atau berubah untuk meningkatkan layanan."],
  ["2. Persyaratan Pengguna", "Anda harus memberikan data yang benar, lengkap, dan terbaru saat membuat akun. Satu akun hanya boleh digunakan oleh satu orang dan tidak boleh dijual, dipinjamkan, dibagikan, atau dialihkan kepada pihak lain. Anda bertanggung jawab menjaga kerahasiaan password dan seluruh aktivitas pada akun Anda."],
  ["3. Membership Pro", "Membership Pro memberikan akses selama 30 hari sejak pembayaran berhasil dikonfirmasi, kecuali keterangan pada halaman penawaran menyatakan lain. Masa aktif yang masih tersisa dapat diperpanjang sesuai kebijakan layanan. Membership tidak otomatis diperpanjang kecuali dinyatakan secara jelas pada saat pembelian. Akses dapat dibatasi apabila membership berakhir, pembayaran gagal, atau akun melanggar ketentuan ini."],
  ["4. Pembayaran", "Pembayaran dilakukan melalui payment gateway Duitku pada lingkungan dan metode pembayaran yang tersedia. Harga yang berlaku adalah harga yang tampil pada halaman checkout. Status pembayaran ditentukan berdasarkan konfirmasi Duitku; setelah notifikasi yang valid diterima, sistem dapat mengaktifkan membership secara otomatis. Jangan melakukan pembayaran berulang untuk invoice yang sama tanpa menghubungi kami."],
  ["5. Kebijakan Pengembalian Dana", "Karena DowaLabs merupakan produk digital yang memberikan akses segera setelah pembayaran dikonfirmasi, pembayaran pada umumnya tidak dapat dibatalkan atau dikembalikan setelah membership aktif. Permintaan peninjauan dapat diajukan jika terjadi pembayaran ganda, kesalahan teknis yang terverifikasi, atau pembayaran berhasil tetapi akses tidak aktif. Hubungi kami dengan nomor invoice, email akun, bukti pembayaran, dan kronologi. Pengembalian dana—jika disetujui—dilakukan melalui metode yang dianggap sesuai dan dapat dipotong biaya administrasi pihak ketiga."],
  ["6. Input dan Output AI", "Anda hanya boleh mengunggah gambar, teks, merek, dan materi lain yang Anda miliki atau berhak gunakan. Anda bertanggung jawab atas instruksi dan materi yang dimasukkan serta wajib meninjau output AI sebelum dipublikasikan atau digunakan untuk penjualan. Output AI dapat tidak akurat, tidak unik, atau tidak selalu sesuai harapan; DowaLabs tidak menjamin output bebas dari kemiripan dengan karya pihak lain atau cocok untuk tujuan tertentu."],
  ["7. Penggunaan yang Dilarang", "Anda dilarang menggunakan layanan untuk melanggar hukum, menipu, menyesatkan konsumen, melanggar hak cipta/merek/potret/privasi, membuat konten seksual eksplisit atau eksploitasi anak, ujaran kebencian, kekerasan, malware, spam, atau konten lain yang membahayakan pihak lain. Dilarang pula melakukan scraping, reverse engineering, mengakali pembatasan akses, mengotomatisasi penggunaan secara berlebihan, atau menyalin dan menjual kembali prompt, template, materi, maupun akses DowaLabs."],
  ["8. Hak Kekayaan Intelektual", "Nama, logo, desain, kode, materi tutorial, prompt, template, dan konten DowaLabs adalah milik DowaLabs atau pemberi lisensinya. Membership hanya memberikan lisensi terbatas, non-eksklusif, dan tidak dapat dialihkan untuk menggunakan layanan selama masa aktif. Anda tetap bertanggung jawab memastikan penggunaan output dan aset pihak ketiga mematuhi lisensi serta hukum yang berlaku."],
  ["9. Ketersediaan dan Pihak Ketiga", "Layanan dapat mengalami pemeliharaan, gangguan, batasan kapasitas, atau perubahan karena ketergantungan pada penyedia AI, hosting, payment gateway, dan layanan pihak ketiga. DowaLabs tidak menjamin layanan selalu tersedia tanpa gangguan dan tidak bertanggung jawab atas gangguan yang sepenuhnya berasal dari pihak ketiga, sepanjang diizinkan hukum."],
  ["10. Penangguhan dan Penghapusan Akun", "Kami dapat menangguhkan atau menghapus akun yang melanggar ketentuan ini, melakukan penipuan, menyalahgunakan layanan, atau menimbulkan risiko keamanan. Penangguhan karena pelanggaran tidak otomatis memberikan hak refund. Anda dapat meminta penghapusan akun melalui kontak resmi; kewajiban yang telah timbul tetap berlaku."],
  ["11. Batas Tanggung Jawab", "DowaLabs disediakan sebagaimana tersedia. Sepanjang diizinkan hukum, kami tidak bertanggung jawab atas kehilangan keuntungan, kehilangan data, kerugian tidak langsung, atau kerugian akibat keputusan bisnis yang dibuat berdasarkan output AI. Ketentuan ini tidak menghapus tanggung jawab yang tidak dapat dikesampingkan berdasarkan hukum Indonesia."],
  ["12. Perubahan Ketentuan", "Kami dapat memperbarui Syarat & Ketentuan ini dari waktu ke waktu. Versi terbaru akan dipublikasikan di halaman ini dengan tanggal pembaruan. Dengan terus menggunakan layanan setelah perubahan berlaku, Anda menyetujui ketentuan yang telah diperbarui."],
  ["13. Hukum dan Kontak", "Ketentuan ini ditafsirkan berdasarkan hukum Republik Indonesia. Untuk pertanyaan, kendala pembayaran, atau permintaan peninjauan, hubungi dowatech889@gmail.com atau WhatsApp 0822 9738 2109 dengan mencantumkan email akun dan nomor invoice bila relevan."],
] as const;

export default function TermsPage() {
  return <div className="container max-w-4xl py-16 sm:py-24"><LocalizedTitle id="Syarat & Ketentuan" en="Terms & Conditions" /><p className="text-xs font-semibold uppercase tracking-[0.2em] text-amber-300">Legal</p><h1 className="mt-4 text-4xl font-semibold tracking-tight sm:text-5xl">Syarat &amp; Ketentuan</h1><p className="mt-5 text-sm text-slate-400">Terakhir diperbarui: 27 Juli 2026</p><div className="mt-12 space-y-9 text-sm leading-7 text-slate-300">{sections.map(([title, text]) => <section key={title}><h2 className="text-lg font-semibold text-white">{title}</h2><p className="mt-2">{text}</p></section>)}</div></div>;
}
